[[projects]]
name = "Chip8 Emulator"
description = "This is a very simple processor. Everyone who want to develop emulators starts with such a project."
mine = ""
[[projects.res]]
title = "Cool article"
link = "https://tobiasvl.github.io/blog/write-a-chip-8-emulator/"

[[projects]]
name = "Personal website"
description = "Everybody need one nowadays"
mine = ""

[[projects]]
name = "CMS engine"
description = "CMS stands for content managment system. Kinda useful thing in big companies. You will probably learn something new while doing this."
mine = ""
