[[projects]]
name = "Chip8 Emulator"
description = "This is a very simple processor. Everyone who want to develop emulators starts with such a project."
mine = ""
[[projects.res]]
title = "Cool article"
link = "https://tobiasvl.github.io/blog/write-a-chip-8-emulator/"
